### ISSUE TITLE
just dose not work!

### ISSUE THREAD

**Issue by shapes9** [Kirpal/Keyboard-Layout-Editor-for-Blender#64]
![2020-09-26 (1)](https://user-images.githubusercontent.com/67300553/94336223-c3e01f80-0024-11eb-8251-9ab9cf8621dc.png)
please fix. i used to do this all the time but now it just doesn't seem to work  :(

**Comment by sanje2v** [comment]
This might be because you're using a newer version of Blender like 2.90.0 with has changed the python add-on API.

I solved this issue by editing the file 'add_label.py' at '%USERPROFILE%\AppData\Roaming\Blender Foundation\Blender\<YOUR BLENDER VERSION>\scripts\addons\keyboard-layout-editor-for-blender'. Find all instances of 'bpy.ops.object.modifier_apply' and delete the 'apply_as' parameter and value to the function.

For example: At line 114, change bpy.ops.object.modifier_apply(apply_as='DATA', modifier="Remesh") to bpy.ops.object.modifier_apply(modifier="Remesh").

Do so for all occurrences in the same file. Save it, reload Blender and then try importing the JSON file again.

**Comment by Kirpal** [comment]
Should be fixed with the latest version!
